controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: ros2_controllers/DiffDriveController


joint_state_broadcaster:
  ros__parameters:
    extra_joints: [
      "rear_right_roller_0_joint",
      "rear_right_roller_1_joint",
      "rear_right_roller_2_joint",
      "rear_right_roller_3_joint",
      "rear_right_roller_4_joint",
      "rear_right_roller_5_joint",
      "rear_right_roller_6_joint",
      "rear_right_roller_7_joint",
      "rear_right_roller_8_joint",
      "rear_left_roller_0_joint",
      "rear_left_roller_1_joint",
      "rear_left_roller_2_joint",
      "rear_left_roller_3_joint",
      "rear_left_roller_4_joint",
      "rear_left_roller_5_joint",
      "rear_left_roller_6_joint",
      "rear_left_roller_7_joint",
      "rear_left_roller_8_joint",
      "front_left_roller_0_joint",
      "front_left_roller_1_joint",
      "front_left_roller_2_joint",
      "front_left_roller_3_joint",
      "front_left_roller_4_joint",
      "front_left_roller_5_joint",
      "front_left_roller_6_joint",
      "front_left_roller_7_joint",
      "front_left_roller_8_joint",
      "front_right_roller_0_joint",
      "front_right_roller_1_joint",
      "front_right_roller_2_joint",
      "front_right_roller_3_joint",
      "front_right_roller_4_joint",
      "front_right_roller_5_joint",
      "front_right_roller_6_joint",
      "front_right_roller_7_joint",
      "front_right_roller_8_joint"]

test_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.5027
    wheel_radius: 0.2032

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: false
    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.max_velocity: .NAN
    linear.x.min_velocity: .NAN
    linear.x.max_acceleration: .NAN
    linear.x.max_deceleration: .NAN
    linear.x.max_acceleration_reverse: .NAN
    linear.x.max_deceleration_reverse: .NAN
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: .NAN
    angular.z.min_velocity: .NAN
    angular.z.max_acceleration: .NAN
    angular.z.max_deceleration: .NAN
    angular.z.max_acceleration_reverse: .NAN
    angular.z.max_deceleration_reverse: .NAN
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN

