twist_mux:
  ros__parameters:
    topics:
      joy:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 10
      keyboard:
        topic: cmd_vel_keyboard
        timeout: 0.5
        priority: 5
